name: Compile AutoHotkey scripts
on:
  push:
    tags:
      - "*"
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: sudo apt -y install curl unzip jq dos2unix
      - name: Convert setup.sh to LF to be sure
        run: dos2unix ./.github/scripts/setup.sh
        shell: bash
      - name: Download AutoHotkey
        run: ./.github/scripts/setup.sh
        shell: bash
      - name: Upload AutoHotkey download
        uses: actions/upload-artifact@v3
        with:
          name: ahk
          path: AutoHotkey
  compile:
    needs: setup
    name: Compile all AutoHotkey scripts
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download AutoHotkey download
        uses: actions/download-artifact@v3
        with:
          name: ahk
          path: AutoHotkey
      - name: Execute the compile script
        shell: bash
        run: .github/scripts/compile.sh
      - name: Upload AutoHotkey output
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: output

  release:
    runs-on: ubuntu-latest
    needs: compile
    name: Generate a release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download AutoHotkey output
        uses: actions/download-artifact@v3
        with:
          name: output
          path: output
      - name: zip the output
        shell: bash
        run: |
          mv icons output
          mkdir -p output/Lib
          cp Lib/VirtualDesktopAccessor.dll output/Lib
          cp Lib/VirtualDesktopAccessor11.dll output/Lib
          sudo apt install -y zip
          zip -r output.zip output
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "output.zip"
          bodyFile: "RELEASE.md"
          token: ${{ secrets.GITHUB_TOKEN }}
